/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// Placeholder — regenerated by @tanstack/router-plugin on `vite dev` / `vite build`.
// We ship a minimal stub so `bun install` + `tsc --noEmit` work before the
// first dev/build cycle.

import { Route as rootRouteImport } from "./routes/__root";

export const routeTree = rootRouteImport;
